# Generated by Django 3.1.12 on 2025-11-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('topic', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('referencing', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Harvard', 'Harvard'), ('Chicago', 'Chicago'), ('IEEE', 'IEEE'), ('Vancouver', 'Vancouver'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('writer_final_file', models.FileField(blank=True, null=True, upload_to='jobs/writer_files/')),
                ('writer_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('allocator', models.ForeignKey(blank=True, limit_choices_to={'role': 'allocator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs', to=settings.AUTH_USER_MODEL)),
                ('process_member', models.ForeignKey(blank=True, limit_choices_to={'role': 'process'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_jobs', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, limit_choices_to={'role': 'writer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'process_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('check', 'Check Stage'), ('final', 'Final Stage'), ('decoration', 'Decoration Stage')], max_length=20)),
                ('ai_file', models.FileField(blank=True, null=True, upload_to='process/ai_files/')),
                ('plag_file', models.FileField(blank=True, null=True, upload_to='process/plag_files/')),
                ('final_file', models.FileField(blank=True, null=True, upload_to='process/final_files/')),
                ('grammarly_report', models.FileField(blank=True, null=True, upload_to='process/grammarly/')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='process/other_files/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_submissions', to='process.job')),
                ('process_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Submission',
                'verbose_name_plural': 'Process Submissions',
                'db_table': 'process_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_comments/attachments/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='process.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Comment',
                'verbose_name_plural': 'Job Comments',
                'db_table': 'job_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecorationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_file', models.FileField(blank=True, null=True, upload_to='decoration/final_files/')),
                ('ai_file', models.FileField(blank=True, null=True, upload_to='decoration/ai_files/')),
                ('plag_file', models.FileField(blank=True, null=True, upload_to='decoration/plag_files/')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='decoration/other_files/')),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_decorations', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_task', to='process.job')),
                ('process_member', models.ForeignKey(limit_choices_to={'role': 'process'}, on_delete=django.db.models.deletion.CASCADE, related_name='decoration_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decoration Task',
                'verbose_name_plural': 'Decoration Tasks',
                'db_table': 'decoration_tasks',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
