# Generated by Django 3.1.12 on 2025-11-19 07:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import marketing.models


def _get_collection(model, schema_editor):
    db = schema_editor.connection.connection
    return db[model._meta.db_table]


def create_indexes(apps, schema_editor):
    Job = apps.get_model('marketing', 'Job')
    JobActionLog = apps.get_model('marketing', 'JobActionLog')
    JobSummaryVersion = apps.get_model('marketing', 'JobSummaryVersion')
    
    job_collection = _get_collection(Job, schema_editor)
    joblog_collection = _get_collection(JobActionLog, schema_editor)
    jobsummary_collection = _get_collection(JobSummaryVersion, schema_editor)
    
    job_indexes = [
        ([('system_id', 1)], 'marketing_j_system__384b1b_idx'),
        ([('job_id', 1)], 'marketing_j_job_id_58215c_idx'),
        ([('status', 1)], 'marketing_j_status_1e42d9_idx'),
        ([('created_by_id', 1)], 'marketing_j_created_5fa37f_idx'),
    ]
    action_indexes = [
        ([('job_id', 1)], 'job_action__job_id_94cf25_idx'),
        ([('timestamp', 1)], 'job_action__timesta_7e6ca7_idx'),
    ]
    summary_indexes = [
        ([('job_id', 1), ('version_number', 1)], 'job_summary_job_id_08c70f_idx'),
    ]
    
    def ensure(collection, specs):
        for spec, name in specs:
            try:
                collection.create_index(spec, name=name)
            except Exception as exc:
                if 'already exists' in str(exc):
                    continue
                raise
    
    ensure(job_collection, job_indexes)
    ensure(joblog_collection, action_indexes)
    ensure(jobsummary_collection, summary_indexes)


def drop_indexes(apps, schema_editor):
    Job = apps.get_model('marketing', 'Job')
    JobActionLog = apps.get_model('marketing', 'JobActionLog')
    JobSummaryVersion = apps.get_model('marketing', 'JobSummaryVersion')
    
    job_collection = _get_collection(Job, schema_editor)
    joblog_collection = _get_collection(JobActionLog, schema_editor)
    jobsummary_collection = _get_collection(JobSummaryVersion, schema_editor)
    
    job_indexes = [
        'marketing_j_system__384b1b_idx',
        'marketing_j_job_id_58215c_idx',
        'marketing_j_status_1e42d9_idx',
        'marketing_j_created_5fa37f_idx',
    ]
    action_indexes = [
        'job_action__job_id_94cf25_idx',
        'job_action__timesta_7e6ca7_idx',
    ]
    summary_indexes = [
        'job_summary_job_id_08c70f_idx',
    ]
    
    def drop(collection, names):
        for name in names:
            try:
                collection.drop_index(name)
            except Exception:
                continue
    
    drop(job_collection, job_indexes)
    drop(joblog_collection, action_indexes)
    drop(jobsummary_collection, summary_indexes)




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('job_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('instruction', models.TextField(help_text='Minimum 50 characters required')),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('referencing_style', models.CharField(blank=True, choices=[('harvard', 'Harvard'), ('apa', 'APA'), ('mla', 'MLA'), ('ieee', 'IEEE'), ('vancouver', 'Vancouver'), ('chicago', 'Chicago')], max_length=20, null=True)),
                ('writing_style', models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('report', 'Report'), ('essay', 'Essay'), ('dissertation', 'Dissertation'), ('business_report', 'Business Report'), ('personal_development', 'Personal Development'), ('reflection_writing', 'Reflection Writing'), ('case_study', 'Case Study')], max_length=30, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('ai_summary_version', models.IntegerField(default=0)),
                ('ai_summary_generated_at', models.JSONField(blank=True, default=list)),
                ('job_card_degree', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold'), ('query', 'Query'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_form_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('initial_form_last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('job_name_validated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary_requested_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_allocated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'marketing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSummaryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('referencing_style', models.CharField(blank=True, max_length=20, null=True)),
                ('writing_style', models.CharField(blank=True, max_length=30, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('degree', models.IntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.CharField(default='system', max_length=50)),
                ('ai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_versions', to='marketing.job')),
            ],
            options={
                'db_table': 'job_summary_versions',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marketing.models.job_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing.job')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('initial_form_submitted', 'Initial Form Submitted'), ('initial_form_saved', 'Initial Form Saved'), ('job_name_validated', 'Job Name Validated'), ('ai_summary_requested', 'AI Summary Requested'), ('ai_summary_generated', 'AI Summary Generated'), ('ai_summary_accepted', 'AI Summary Accepted'), ('status_changed', 'Status Changed'), ('allocated', 'Allocated'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=50)),
                ('performed_by_type', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='marketing.job')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_action_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_indexes, drop_indexes)
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='jobsummaryversion',
                    index=models.Index(fields=['job', 'version_number'], name='job_summary_job_id_08c70f_idx'),
                ),
                migrations.AddIndex(
                    model_name='jobactionlog',
                    index=models.Index(fields=['job'], name='job_action__job_id_94cf25_idx'),
                ),
                migrations.AddIndex(
                    model_name='jobactionlog',
                    index=models.Index(fields=['timestamp'], name='job_action__timesta_7e6ca7_idx'),
                ),
                migrations.AddIndex(
                    model_name='job',
                    index=models.Index(fields=['system_id'], name='marketing_j_system__384b1b_idx'),
                ),
                migrations.AddIndex(
                    model_name='job',
                    index=models.Index(fields=['job_id'], name='marketing_j_job_id_58215c_idx'),
                ),
                migrations.AddIndex(
                    model_name='job',
                    index=models.Index(fields=['status'], name='marketing_j_status_1e42d9_idx'),
                ),
                migrations.AddIndex(
                    model_name='job',
                    index=models.Index(fields=['created_by'], name='marketing_j_created_5fa37f_idx'),
                ),
            ]
        ),
    ]
