# Generated by Django 3.1.12 on 2025-11-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadminpanel', '0007_auto_20251122_1504'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('NON-IT', 'Non-IT'), ('Finance', 'Finance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='final_form_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='final_form_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='masking_id_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_jobs', to='superadminpanel.projectgroupmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='strict_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='system_expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_jobs', to='superadminpanel.templatemaster'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('completed', 'Completed'), ('hold', 'Hold'), ('query', 'Query'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
