# Generated by Django 3.1.12 on 2025-11-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20251122_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('NON-IT', 'Non-IT'), ('FINANCE', 'Finance')], max_length=20, null=True),
        ),
    ]
