# Generated by Django 3.1.12 on 2025-11-24 09:33

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20251122_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
    ]
