# Generated by Django 3.1.12 on 2025-11-26 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0005_job_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text='Minimum 3 characters required', max_length=255)),
                ('customer_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('customer_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('targeted_amount', models.DecimalField(decimal_places=2, help_text='Target amount in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Current amount accumulated from jobs', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('cancelled_projects', models.IntegerField(default=0)),
                ('projects_with_issues', models.IntegerField(default=0)),
                ('total_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('it_projects', models.IntegerField(default=0)),
                ('non_it_projects', models.IntegerField(default=0)),
                ('finance_projects', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'marketing_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Customer ID from marketing_customers', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name captured at final submission', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomerActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('kpi_updated', 'KPI Updated')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='marketing.customer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_action_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='customeractionlog',
            index=models.Index(fields=['customer'], name='customer_ac_custome_4647a8_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractionlog',
            index=models.Index(fields=['timestamp'], name='customer_ac_timesta_41aecc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_id'], name='marketing_c_custome_4f3061_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_email'], name='marketing_c_custome_fbfc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='marketing_c_is_acti_5981d8_idx'),
        ),
    ]
