# Generated by Django 3.1.12 on 2025-11-14 10:07

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251114_1416'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
    ]
