# Generated by Django 3.1.12 on 2025-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('user_lifecycle', 'User Lifecycle'), ('superadmin', 'Superadmin / Manage Users'), ('employee_id', 'Employee ID'), ('holiday_master', 'Holiday Master'), ('general', 'General')], db_index=True, default='general', max_length=32),
        ),
    ]
