# Generated by Django 3.1.12 on 2025-11-19 07:30

from django.db import migrations, models


def _get_collection(model, schema_editor):
    db = schema_editor.connection.connection
    return db[model._meta.db_table]


def create_indexes(apps, schema_editor):
    ActivityLog = apps.get_model('accounts', 'ActivityLog')
    collection = _get_collection(ActivityLog, schema_editor)
    index_specs = [
        ([('event_key', 1)], 'activity_lo_event_k_f34a0e_idx'),
        ([('category', 1)], 'activity_lo_categor_0f5b7d_idx'),
        ([('created_at', 1)], 'activity_lo_created_166e11_idx'),
    ]
    
    for spec, name in index_specs:
        try:
            collection.create_index(spec, name=name)
        except Exception as exc:  # pragma: no cover
            if 'already exists' in str(exc):
                continue
            raise


def drop_indexes(apps, schema_editor):
    ActivityLog = apps.get_model('accounts', 'ActivityLog')
    collection = _get_collection(ActivityLog, schema_editor)
    index_names = [
        'activity_lo_event_k_f34a0e_idx',
        'activity_lo_categor_0f5b7d_idx',
        'activity_lo_created_166e11_idx',
    ]
    
    for name in index_names:
        try:
            collection.drop_index(name)
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20251118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('user_lifecycle', 'User Lifecycle'), ('superadmin', 'Superadmin / Manage Users'), ('employee_id', 'Employee ID'), ('holiday_master', 'Holiday Master'), ('job_management', 'Job Management'), ('general', 'General')], db_index=True, default='general', max_length=32),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_indexes, drop_indexes)
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='activitylog',
                    index=models.Index(fields=['event_key'], name='activity_lo_event_k_f34a0e_idx'),
                ),
                migrations.AddIndex(
                    model_name='activitylog',
                    index=models.Index(fields=['category'], name='activity_lo_categor_0f5b7d_idx'),
                ),
                migrations.AddIndex(
                    model_name='activitylog',
                    index=models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'),
                ),
            ]
        ),
    ]
