# Generated by Django 3.1.12 on 2025-11-17 09:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('pending_projects', models.PositiveIntegerField(default=0)),
                ('in_progress_projects', models.PositiveIntegerField(default=0)),
                ('issues_count', models.PositiveIntegerField(default=0)),
                ('hold_count', models.PositiveIntegerField(default=0)),
                ('total_words_written', models.PositiveIntegerField(default=0)),
                ('on_time_delivery', models.PositiveIntegerField(default=0)),
                ('late_delivery', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('writer', models.OneToOneField(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='writer_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writer Statistics',
                'verbose_name_plural': 'Writer Statistics',
                'db_table': 'writer_statistics',
            },
        ),
        migrations.CreateModel(
            name='WriterProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('topic', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('referencing', models.CharField(choices=[('apa', 'APA'), ('mla', 'MLA'), ('harvard', 'Harvard'), ('chicago', 'Chicago'), ('ieee', 'IEEE'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold'), ('issues', 'Issues'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submission_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'allocator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_projects', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='writer_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writer Project',
                'verbose_name_plural': 'Writer Projects',
                'db_table': 'writer_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('technical', 'Technical Issue'), ('clarification', 'Need Clarification'), ('resources', 'Missing Resources'), ('deadline', 'Deadline Extension'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='writer.writerproject')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Issue',
                'verbose_name_plural': 'Project Issues',
                'db_table': 'project_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='writer.writerproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Comment',
                'verbose_name_plural': 'Project Comments',
                'db_table': 'project_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
