# Generated by Django 3.1.12 on 2025-11-15 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBankingResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('banking_sectors', models.JSONField(default=list)),
                ('other_resources', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'country_banking_resources',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masking_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('topic', models.TextField()),
                ('client_name', models.CharField(max_length=255)),
                ('job_category', models.CharField(choices=[('IT', 'IT'), ('NONIT', 'Non-IT'), ('Finance', 'Finance')], max_length=20)),
                ('software_type', models.CharField(blank=True, choices=[('management_withsoftware', 'Management with Software'), ('management_withoutsoftware', 'Management without Software'), ('IT_withsoftware', 'IT with Software'), ('IT_withoutsoftware', 'IT without Software'), ('finance_withsoftware', 'Finance with Software'), ('finance_withoutsoftware', 'Finance without Software')], max_length=50, null=True)),
                ('degree', models.IntegerField(choices=[(0, '0 Degree'), (1, '1 Degree'), (2, '2 Degree'), (3, '3 Degree'), (4, '4 Degree'), (5, '5 Degree')], default=0)),
                ('word_count', models.IntegerField()),
                ('max_word_limit', models.IntegerField(help_text='Maximum word limit allowed')),
                ('description', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('marketing_comment', models.TextField(blank=True, null=True)),
                ('allocator_comment', models.TextField(blank=True, null=True)),
                ('allocator_comment_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Allocation'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('hold', 'On Hold'), ('query', 'Query'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('structure_file', models.FileField(blank=True, null=True, upload_to='job_structures/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('banking_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('has_query', models.BooleanField(default=False)),
                ('query_count', models.IntegerField(default=0)),
                ('allocated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'allocator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'marketing'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_writer', models.BooleanField(default=False, help_text='Can handle IT jobs')),
                ('is_nonit_writer', models.BooleanField(default=True, help_text='Can handle Non-IT jobs')),
                ('is_finance_writer', models.BooleanField(default=True, help_text='Can handle Finance jobs')),
                ('is_available', models.BooleanField(default=True)),
                ('is_sunday_off', models.BooleanField(default=False)),
                ('is_on_holiday', models.BooleanField(default=False)),
                ('is_overloaded', models.BooleanField(default=False)),
                ('max_jobs', models.IntegerField(default=5, help_text='Maximum concurrent jobs')),
                ('current_jobs', models.IntegerField(default=0)),
                ('max_words', models.IntegerField(default=0, help_text='Maximum words can handle')),
                ('current_words', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('total_jobs_assigned', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'writer'}, on_delete=django.db.models.deletion.CASCADE, related_name='writer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writer_profiles',
            },
        ),
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('content_creation', 'Content Creation'), ('ai_plag', 'AI & Plagiarism Check'), ('decoration', 'Decoration')], max_length=30)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'On Hold'), ('query', 'Query')], default='pending', max_length=20)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('ai_summary_file', models.FileField(blank=True, null=True, upload_to='ai_summaries/')),
                ('final_file', models.FileField(blank=True, null=True, upload_to='final_submissions/')),
                ('temperature_matched', models.BooleanField(default=False)),
                ('temperature_score', models.FloatField(blank=True, null=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_tasks', to=settings.AUTH_USER_MODEL)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocations', to='allocator.job')),
            ],
            options={
                'db_table': 'task_allocations',
                'ordering': ['job', 'task_type'],
                'unique_together': {('job', 'task_type')},
            },
        ),
        migrations.CreateModel(
            name='ProcessTeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_sunday_off', models.BooleanField(default=False)),
                ('is_on_holiday', models.BooleanField(default=False)),
                ('max_jobs', models.IntegerField(default=5)),
                ('current_jobs', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'process'}, on_delete=django.db.models.deletion.CASCADE, related_name='process_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_team_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='allocator.job')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_queries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_queries', to=settings.AUTH_USER_MODEL)),
                ('task_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='allocator.taskallocation')),
            ],
            options={
                'db_table': 'job_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allocated', 'Allocated'), ('reallocated', 'Reallocated'), ('switched', 'Switched Writer'), ('edited', 'Edited'), ('cancelled', 'Cancelled')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_changes', to=settings.AUTH_USER_MODEL)),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_allocations', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_allocations', to=settings.AUTH_USER_MODEL)),
                ('task_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='allocator.taskallocation')),
            ],
            options={
                'db_table': 'allocation_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['masking_id'], name='jobs_masking_36e61d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'job_category'], name='jobs_status_bdc712_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by', 'status'], name='jobs_created_1f97f3_idx'),
        ),
    ]
