# Generated by Django 3.1.12 on 2025-11-22 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocator', '0003_taskallocation_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskallocation',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_allocations_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
