# Generated by Django 3.1.12 on 2025-11-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=20)),
                ('date_type', models.CharField(choices=[('single', 'Single'), ('consecutive', 'Consecutive Days')], default='single', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_calendar_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_synced_at', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_sync_failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['-created_at'],
            },
        ),
    ]
