# Generated by Django 3.1.12 on 2025-11-20 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0002_auto_20251118_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'NON-IT')], max_length=20)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=20)),
                ('price_per_word', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Master',
                'verbose_name_plural': 'Price Masters',
                'db_table': 'price_master',
                'ordering': ['-created_at'],
                'unique_together': {('category', 'level')},
            },
        ),
    ]
