# Generated by Django 3.1.12 on 2025-11-20 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0003_pricemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencing_style', models.CharField(max_length=255)),
                ('used_in', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_styles_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_styles_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_styles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referencing Style',
                'verbose_name_plural': 'Referencing Styles',
                'db_table': 'referencing_master',
                'ordering': ['-created_at'],
                'unique_together': {('referencing_style', 'used_in')},
            },
        ),
    ]
