# Generated by Django 3.1.12 on 2025-11-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0004_referencingmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencingmaster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referencing Master', 'verbose_name_plural': 'Referencing Masters'},
        ),
        migrations.AlterField(
            model_name='referencingmaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencingmaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencingmaster',
            name='referencing_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencingmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referencingmaster',
            unique_together=set(),
        ),
    ]
