# Generated by Django 3.1.12 on 2025-11-22 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadminpanel', '0006_academicwritingmaster_projectgroupmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_description', models.TextField(blank=True, null=True)),
                ('default_tasks', models.JSONField(default=list, help_text='Default tasks that will be created when this template is used')),
                ('visibility_config', models.JSONField(default=dict, help_text='Configuration for field visibility per role')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Master',
                'verbose_name_plural': 'Template Masters',
                'db_table': 'template_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masking_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('project_prefix', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masking_id_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_template', to='marketing.job')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_templates', to='superadminpanel.projectgroupmaster')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_instances', to='superadminpanel.templatemaster')),
            ],
            options={
                'db_table': 'job_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('task_number', models.IntegerField()),
                ('task_name', models.CharField(max_length=255)),
                ('task_code', models.CharField(max_length=10)),
                ('assignable_roles', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('completed_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total work hours spent on this task', max_digits=10)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('job_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='superadminpanel.jobtemplate')),
            ],
            options={
                'db_table': 'job_tasks',
                'ordering': ['task_number'],
            },
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['task_id'], name='job_tasks_task_id_59de1c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['status'], name='job_tasks_status_61577e_idx'),
        ),
    ]
